name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y libgtest-dev cmake
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .  # This builds your project

    - name: Run tests
      run: |
        cd build
        ctest --verbose  # Run the tests with CTest and show detailed output
