name: Build and Test C++ Project

# Run on pushes to the main branch or on pull requests
on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  pull_request:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to macos-latest or windows-latest if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checks out your repository's code

    - name: Set up CMake
      uses: actions/setup-cmake@v3  # Sets up CMake on the runner
      with:
        cmake-version: '3.21'  # Change this to the desired version of CMake

    - name: Set up GCC
      uses: actions/setup-gcc@v1
      with:
        gcc-version: '10'  # Choose a GCC version that matches your project

    - name: Create build directory
      run: cd tests && mkdir -p build && cd build

    - name: Build project
      run: |
        cd build
        cmake ..
        cmake --build .  # This builds your project

    - name: Run tests
      run: |
        cd build
        ctest --verbose  # Run the tests with CTest and show detailed output
